version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8084:80"
        volumes:
            - ./dist:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - VIRTUAL_HOST=classificacaoderisco.luisdevelopment.ml
        networks:
            - web
networks:
  web:
    external: true


